### PR TITLE
Add MySQL Reader

### PR DESCRIPTION
**Pull request by gwukelic**
Adding equivalent support to MySQL.

### CODE REVIEW

**Comment by criccomini** [comment]
🤯 yasss, thanks for this! I'll take a look tomorrow. Kinda burnt on the JSON metaschema stuff from today, so taking a break. 😃

**Review by criccomini — CHANGES_REQUESTED** [review]
Looks great! No commends on code. Looks largely the same as the PG one.

Request: Mind adding a MySQL integration test similar to PG's?

**Comment by criccomini** [comment]
Gonna try to take control and fix this. It's just junk work remaining that I can take care of easily.

**Comment by criccomini** [comment]
@gwukelic can you grant me write access to your fork or branch?

**Comment by criccomini** [comment]
Note to self: three things to be done:

1. `pdm add -dG tests mysql-connector-python`
2. Add `mysql` block to `integration-tests`

```yaml
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

3. Change port to `3306` in `test_mysql.py`
4. Add `# For MySQL` comment in pyproject.toml `tests` block above `mysql-connector-python` line.

**Comment by gwukelic** [comment]
@criccomini you should have access now! Thank you for getting this over the finish line.

**Comment by criccomini** [comment]
Note: I had to force push. The branch was pretty far behind, and I had to rebase to fix things. Somehow the rebase got all wonky and I couldn't push anymore. Sorry about that. :(

**Comment by criccomini** [comment]
@gwukelic Merged, thanks for the contribution! I discovered a bunch of bugs once the real integration test got running. I went through and fixed them according to the MySQL docs. The only two real notes:

1. JSON column sizes aren't exactly accurate since MySQL stores JSON structure in a [compact binary representation](https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-json).
2. BIT columns are using 8 bytes (64 bit max), though I think technically they can vary in size (`BIT(M)`).

I should also note that sizes are storage-engine dependent (innodb vs. myisam vs. ndb and so on). The `octet_length` field should handle most of this automatically, though.

**Comment by criccomini** [comment]
Added docs to recap.build:

https://recap.build/docs/readers/mysql/

**Pull request merged**
